### ISSUE TITLE
[Epic] Web.API - Import endpoint

### ISSUE THREAD

**Issue by Alex-Kozachenko** [DeadlockHoliday/Shopping#2]
The goal of this issue is to make a showcase which *successfully* imports supply data.
For further processing.

It's a bit complex goal which includes:
- [x] Create a web-api `csproj`.
- [x] Add dependencies -  All `Contracts`, `Domain/Facade`, `Data` repository.
- [ ] Introduce a service locator which will be able to dynamic bind the `Import` contract with an implementation (this includes all nested dependencies).
- [ ] Make an API demo with mock request. (Which is processed with real code).
- [ ] Introduce a unit-tests for `/Import` endpoint.
- [ ] Make a swagger for `/Import` endpoint.
- [ ] Introduce a bypassing any data to `/Import` endpoint so it gonna work as complete product.

**Comment by Alex-Kozachenko** [comment]
*Maybe* I will spawn a sub-issue when the related work gonna take a few days or even an iteration.

**Comment by Alex-Kozachenko** [comment]
It's been like, 10 days ago.
I went for a weekend.
Afterwards, I got a huge stress. Decided to take a day off. A second, and so on.
Ends up a week off, or so.

I was reading some books on ASP.NET Core.
Tried some Peter Buck or something, from 2021. Thought he gonna show me something new. But nope, the Core 3.1 right there.

So I returned back to the Adam Freeman and gonna be a week off or so, until the Part III is learned on my side.

This decision is came up from a confusion during just by looking at modern ASP.NET Program.cs file.
I dont wanna wildguesses anymore. I want a solid basics.
