### ISSUE TITLE
Layer out the design

### ISSUE THREAD

**Issue by DeadlockHoliday** [DeadlockHoliday/Shopping#39]
- [x] Extract projects into separated git submodules.
- [x] Introduce a local NuGet solution, for Data, Common...
- [x] Rename submodules (see below)
- [x] Automapper for Data

Data
==============
Looking at Data project, it looks like a encapsulation for database which
a) knows about the `tables` inside;
b) manages mapping between `.net types` and `database fields`;
c) knows about the `Domain Types`.

Decouple data from interface
-----------------------------

I see `a)` and `c)` as a problem here, so the Data layer has extra dependency on the shared library.
The Automapper, (a really popular stuff), could help to separate the Data entirely and I see it as a easier deployment solution.
After all, if `Data` is a repository for a database - it should not know anything beyond that.

Whats about BSON mappings
---------------------------

For now, it looks fine:
```
BsonMapper.Global.RegisterType<Money>
(
    serialize: (money) => money.Amount,
    deserialize: (bson) => new Money(bson.AsDecimal)
);

BsonMapper.Global.RegisterType<JsonNode>
(
    serialize: (jsonNode) => jsonNode.ToJsonString(),
    deserialize: (bson) => JsonNode.Parse(bson.AsString)!
);
```

But later on, it could lead to a problem of overbloating the mappings for every dedicated table, case, whatever. I'd like to separate this, but also I see a case like 50/50. Dont touch for now. 

It gonna get obvious sooner or later.

Rename submodules
=================
I found the solution is messed up already - looking at the solution I cant tell which folder serves for what?
Then, I found that every subproject belongs to separated layer, so the solution should be layered out, as visualized here:

So, the namespaces and folder structure should be:
```
* - omitted parent(s) name(s)
/Shopping
- /*.API
- /*.Cloud.Front
  - *.Readers
- /*.Cloud.Back
  - *.Processing.Products
- /*.Database
  - *.Data
  - *.Repositories
  - ???
```

This one actually makes more sense:
```mermaid
flowchart LR;
  Data[(Data)]
  Contracts.Modules[[Contracts.Modules]]
  Contracts.Modules.Services[[Contracts.Modules.Services]]
  Contracts.Data[[Contracts.Data]]
  Cloud{{Cloud}}
  API{{API}}
  Scheduler{{Scheduler}}

  Data -- Implements
    --> Contracts.Data

  API -- Consumes
    ---> Contracts.Modules

  API -- Consumes
    ---> Contracts.Data

  Scheduler -- Consumes
    ---> Contracts.Modules.Services

  Cloud -- Implements
    --> Contracts.Modules
```

**Comment by DeadlockHoliday** [comment]
![20230315_171541](https://user-images.githubusercontent.com/119358312/225340399-fd64d208-b6c7-41a3-969c-6653856b3934.jpg)

**Comment by DeadlockHoliday** [comment]
I just reworked the design, so no need for Nuget. Just tired of managing microlibraries and coupled up all the `Cloud` packages to a whole, and separated `Data`, so the structure looks like a familiar layered Cloud-Data approach

**Comment by DeadlockHoliday** [comment]
This one actually makes more sense:
```mermaid
flowchart LR;
  Data[(Data)]
  Contracts.Modules[[Contracts.Modules]]
  Contracts.Modules.Services[[Contracts.Modules.Services]]
  Contracts.Data[[Contracts.Data]]
  Cloud{{Cloud}}
  API{{API}}
  Scheduler{{Scheduler}}

  Data -- Implements
    --> Contracts.Data

  API -- Consumes
    ---> Contracts.Modules

  API -- Consumes
    ---> Contracts.Data

  Scheduler -- Consumes
    ---> Contracts.Modules.Services

  Cloud -- Implements
    --> Contracts.Modules
```

**Comment by DeadlockHoliday** [comment]
No need for automapper now
